### ISSUE TITLE
Small issue: SALT cap should not be indexed

### ISSUE THREAD

**Issue by TylerEvilsizer** [PSLmodels/Tax-Brain#101]
It appears that Tax Brain's baseline settings index the $10,000 cap on the state and local tax deduction for inflation, but it should not be. The limit does not increase with inflation...it's $10,000 for all years ($5,000 for married filing separately)

![image](https://user-images.githubusercontent.com/58742743/70549634-87e5d780-1b42-11ea-9551-e78075d947d4.png)

**Comment by hdoupe** [comment]
@TylerEvilsizer thanks for opening this issue!

Tax-Calculator sets this as an indexed parameter (see value of "indexed" in the [parameter definition](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json#L1460-L1505)).

@MattHJensen @Peter-Metz @andersonfrailey Can you comment on whether this parameter should be indexed or not?

**Comment by MattHJensen** [comment]
@TylerEvilsizer is correct that the cap should not be indexed to inflation. I will fix this in Tax-Calculator. Thanks very much for the bug report @TylerEvilsizer!

**Comment by MattHJensen** [comment]
This is now fixed in taxcalc 2.7.0 thanks to a PR from @MaxGhenis. 

@hdoupe, is there something you can do to trigger a rebuild of Tax-Brain on Compute Studio, or do we need a new Tax-Brain release?

**Comment by hdoupe** [comment]
Yep, I'll build it from master. I'll comment back when it's up.

**Comment by TylerEvilsizer** [comment]
Thanks all!

**Comment by hdoupe** [comment]
All set! Tax-Brain, Tax-Cruncher, and Cost-of-Capital-Calculator are all running Tax-Calculator 2.7.0 Thanks again for the bug report @TylerEvilsizer!
