### ISSUE TITLE
Correct output table row labels

### ISSUE THREAD

**Issue by Peter-Metz** [PSLmodels/Tax-Brain#117]
Under the "Current Law" and "Reform" tabs in the output table below, the row labels should not say "change."

<img width="536" alt="Screen Shot 2020-04-15 at 4 16 33 PM" src="https://user-images.githubusercontent.com/43755005/79384278-8aaf6980-7f34-11ea-8f90-facbf2e35b7b.png">

**Comment by andersonfrailey** [comment]
Resolved in PR #120, closing.
