### ISSUE TITLE
Compute benefits totals in aggregate tables

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Brain#119]
Currently, the default aggregate liabilities tables from Tax-Brain report payroll and individual income tax liabilities. But Tax-Brain also allows users to adjust parameters of spending programs such as UBI, Social Security, and unemployment insurance.

It might be useful to have the default liabilities table also report a line for changes in aggregate amounts of spending so that users can see the costs of adjusting these benefits programs.

**Comment by andersonfrailey** [comment]
Resolved in PR #120, closing.
