### ISSUE TITLE
Parameter conversion in cs config

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Brain#127]
https://github.com/PSLmodels/Tax-Brain/blob/517469df91bcd8f36ea864dea2230270f0e8ade6/cs-config/cs_config/functions.py#L25

@hdoupe, now that Tax-Calculator uses paramtools do we still need to convert the policy parameters before creating the `TCParams` class object?

**Comment by hdoupe** [comment]
@andersonfrailey we still have to convert the parameters until the new version of TC is released.

Trust me, I'm counting down the days until we can get rid of (prepare yourself) this:

https://github.com/PSLmodels/Tax-Brain/blob/517469df91bcd8f36ea864dea2230270f0e8ade6/cs-config/cs_config/helpers.py#L130-L171

**Comment by andersonfrailey** [comment]
With the merge of #128 and pending new release of Tax-Brain, this issue can be closed.
