### ISSUE TITLE
Run calculators for n reforms

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Brain#133]
I don't know how useful this would be just yet, but it'd be a cool if TaxBrain could take a list of n reforms and run a calculator under each one. It would require rethinking how TaxBrain stores data from each run and memory management would be a huge issue. I think implementing this should wait until we find a way to reduce TaxBrain's memory issues.

**Comment by jdebacker** [comment]
@andersonfrailey This would be a very good feature, especially if this could be used to generate stacked revenue estimates, with separate line items for each provision.

**Comment by andersonfrailey** [comment]
@jdebacker that's one of the top uses I had in mind. It'll be much easier to add stacked revenue estimates once this feature is added.

**Comment by jdebacker** [comment]
The stacked reform option is currently in Tax-Brian and works well.
