### ISSUE TITLE
Refundable CTC Issue

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Brain#152]
This issue was reported by a user modeling some CTC reforms. Specifically, upping the renewable CTC from $600 to $1500 has no effect when using the PUF. Either way we see a drop in tax liability of ~$91 billion. This is only an issue with the PUF. Liabilities change as expected when you use the CPS. Given this, it's likely a data issue that I haven't gotten to the bottom of yet, but I want to open this up incase there are other ideas. Links to the four runs are below.

cc @MattHJensen 

[CPS - 600](https://compute.studio/PSLmodels/Tax-Brain/49959/)
[CPS - 1500](https://compute.studio/PSLmodels/Tax-Brain/49957/)
[PUF - 600](https://compute.studio/PSLmodels/Tax-Brain/49810/)
[PUF - 1500](https://compute.studio/PSLmodels/Tax-Brain/49809/)

**Comment by jdebacker** [comment]
Closing.  Issue should be discuss in [TaxData](https://github.com/PSLmodels/taxdata).
