### ISSUE TITLE
Convert table function

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Brain#157]
The `report_utils.convert_table()` function is said to convert a DataFrame to markdown. 

Why not just use [`pd.DataFrame.to_markdown()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_markdown.html)?

**Comment by andersonfrailey** [comment]
I'm blanking on the exact details, but I think I ran into some issue with pandoc not converting the tables properly when I used `to_markdown()`. But I ran into enough pandoc issues that I could be mixing them up now. I do know that we use the `convert_table()` function for converting more than just DataFrames though and I wanted all of that to be handled with just one function.

**Comment by jdebacker** [comment]
> we use the convert_table() function for converting more than just DataFrames though and I wanted all of that to be handled with just one function.

Ah - got it!  Closing issue.
