### ISSUE TITLE
Host docs at taxbrain.pslmodels.org?

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Tax-Brain#161]
Now that @jdebacker has moved the docs to jupyter books, @andersonfrailey do you have any thoughts on hosting the docs at https://taxbrain.pslmodels.org?

**Comment by andersonfrailey** [comment]
@hdoupe I'm good with that. What would we need to do for that?

**Comment by hdoupe** [comment]
Sorry @andersonfrailey just saw this comment. Not much at all--I can do everything through the Github and Cloudflare settings. Just need your approval.

**Comment by andersonfrailey** [comment]
Go for it, @hdoupe!

**Comment by hdoupe** [comment]
Done! Sorry for the delay:

https://taxbrain.pslmodels.org

**Comment by andersonfrailey** [comment]
Beautiful. Thanks, @hdoupe! Closing this now that the new website is up.
