### ISSUE TITLE
typing.py

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Brain#162]
@andersonfrailey I can't quite figure out what the purpose of the `typing.py` module is.  Can you help me understand?

**Comment by hdoupe** [comment]
@jdebacker this just defines a few types to help document function signatures.

For example, the `TaxcalcReform` and `ParamToolsAdjustment` are used here:

https://github.com/PSLmodels/Tax-Brain/blob/05984901c87645b630d348a328f3da5588b5ade7/taxbrain/utils.py#L257-L285

Side note: `is_paramtools_format` is now implemented in Tax-Calculator: https://taxcalc.pslmodels.org/api/parameters.html#taxcalc.parameters.is_paramtools_format

**Comment by jdebacker** [comment]
@hdoupe Thanks for the reply.  I haven't used type hinting or see it before.  Just read [this Real Python article](https://realpython.com/lessons/pros-and-cons-type-hints/) and not clear on benefits if you already have docstrings noting the types for the inputs and output of functions.  Can help catch additional errors?

**Comment by chusloj** [comment]
@jdebacker These type hints from the `typing` module are mostly used for type-checking during development in IDEs. However, if you use a static type-checker like [`mypy`](http://mypy-lang.org) you can find errors based on type hints. Also, I think you can use the `typing` module with the built-in `isinstance()` function.

@hdoupe Does this sound correct?

**Comment by MaxGhenis** [comment]
IDEs can also automatically populate the docstring types based on type hints.

**Comment by jdebacker** [comment]
Got it - thanks for all the input on the use of the `typing` package and how type hints can be useful.
