### ISSUE TITLE
CS Release with Tax-Calculator 3.1.0?

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Tax-Brain#163]
@andersonfrailey it might be a good time to do a CS release since TC 3.1.0 fixes some bugs that affect TB users somewhat often. I don't think we necessarily need to do a full release, but I'll defer to you on that.

**Comment by andersonfrailey** [comment]
@hdoupe, I'm good with that. I don't think we need a full TB release for this. Unless I missed something, most PRs merged since the last release were just for CS, not TBs internals.

**Comment by hdoupe** [comment]
Thanks @andersonfrailey. I'll do a push tomorrow and will report back when it's live.

**Comment by hdoupe** [comment]
I'm going to re-open an issue with more current info.
