### ISSUE TITLE
Build package for Python 3.8+

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Brain#167]
It would be helpful to have a Tax-Brain package available for Python 3.8+.  It would play better with other PSL models.

Given the state of Package-Builder, it might be good to move to conda forge for new releases.

**Comment by andersonfrailey** [comment]
+1 to this. I'm planning on doing a new release in the next few days and will try to so using conda forge.

**Comment by andersonfrailey** [comment]
Tax-Brain is live on conda-forge! It can be installed with `conda install -c conda-forge taxbrain` and works in python 3.8 environments.

Thanks to @chusloj for helping out with this.
