### ISSUE TITLE
Identical results for reform analysis selecting CPS and PUF

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Brain#190]
I ran a reform repealing EITC childless age limits through Tax-Brain, and got identical results whether selecting the [CPS](https://compute.studio/PSLmodels/Tax-Brain/53287/) or the [PUF](https://compute.studio/PSLmodels/Tax-Brain/53288).

**Comment by jdebacker** [comment]
Closing as the web app used is no longer running and the error appears on the web app only.
