### ISSUE TITLE
Parameter category naming

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Brain#32]
Currently the major parameter categories are `Behavior` and `Policy`. It might be nice to pair `Policy` with `Assumptions` and make `Behavior` a subcategory of `Assumptions`.

**Comment by MattHJensen** [comment]
This the current manifestation on COMP: 

![image](https://user-images.githubusercontent.com/8301092/55670910-beeb4700-5857-11e9-8c27-da50b9b630c7.png)

Note that `Behavior` is currently a subcategory of `Behavior`, where it could be a subcategory of `Assumptions`.

**Comment by andersonfrailey** [comment]
@MattHJensen, thanks for the suggestion. I can make that change for the next release.

**Comment by andersonfrailey** [comment]
This has been addressed in #38, closing.
