### ISSUE TITLE
Potential confusion for users looking for Tax-Brain

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Brain#41]
I wanted to run Tax-Brain to help me figure out a puzzle I have run into with tc cli.

Wasn't sure how best to access it so I Googled policy simulation models, found that page, drilled down to [this page](https://www.pslmodels.org/Catalog/Tax-Brain.html), which has [Link to webapp](https://www.compmodels.org/PSLmodels/Tax-Brain/), which takes me to the compmodels version.

But I also found the other (older? official?) version at [this link](http://apps.ospc.org/taxbrain), leaving me a little confused as to which was official and which to use.

I pass this on because others might be confused, too. Might be useful to have text somewhere that explains which is which, and maybe links from each to the other.

Also, nitpickers might wonder whether the difference between "TaxBrain" at ospc and "Tax-Brain" at compmodels (one has hyphen and one does not) means they are different models.

**Comment by andersonfrailey** [comment]
Now that the old version of Tax-Brain has been archived, this issue has been taken care of. Closing.
