### ISSUE TITLE
Any planned use of taxcalc.Calculator.read_json_parameters method?

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Brain#9]
Searching the Tax-Brain source code in the late afternoon of 2019-03-06, I see that there is no use being made by Tax-Brain of the `taxcalc.Calculator.read_json_parameters` static method.  I'm assuming that there are no plans to use that method in Tax-Brain, right?  If so, I plan to remove it.

And another question, when would be the right time to remove all the tbi-related code and tests from the Tax-Calculator and Behavioral-Responses repositories?  It seems as if you have moved all the code and tests from those two repositories to the Tax-Brain repository, right?

**Comment by martinholmer** [comment]
@andersonfrailey and @hdoupe, see my two questions in [this comment](https://github.com/PSLmodels/Tax-Brain/issues/9#issue-418046017).

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>Searching the Tax-Brain source code in the late afternoon of 2019-03-06, I see that there is no use being made by Tax-Brain of the taxcalc.Calculator.read_json_parameters static method. I'm assuming that there are no plans to use that method in Tax-Brain, right? If so, I plan to remove it.

There are no plans to use it, correct. If for whatever reason a need comes up down the road we can add it to the Tax-Brain source code so feel free to remove it.

>And another question, when would be the right time to remove all the tbi-related code and tests from the Tax-Calculator and Behavioral-Responses repositories? It seems as if you have moved all the code and tests from those two repositories to the Tax-Brain repository, right?

Yes, the code and tests have been moved to Tax-Brain. I'm going to issue a first release of Tax-Brain, hopefully today, and move the model onto COMP. Once that is complete I'd be comfortable with the TBI related code and tests being removed from Tax-Calculator and Behavioral-Response. If everything goes smoothly that should be done by the end of next week at the latest.

**Comment by martinholmer** [comment]
@andersonfrailey, Thanks for the update on your Tax-Brain development plans in [this comment](https://github.com/PSLmodels/Tax-Brain/issues/9#issuecomment-470547144).
