### ISSUE TITLE
Most benefit switches are not shown in CS UI

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Brain#99]
See https://compute.studio/PSLmodels/Tax-Brain/#Benefits
![image](https://user-images.githubusercontent.com/6076111/70297778-2b7e6300-17a4-11ea-8930-604f63918ca0.png)

**Comment by hdoupe** [comment]
@MaxGhenis Those switches are unavailable when using the PUF. I suppose the UI would be better if something like "Unavailable under current configuration" was shown instead.

**Comment by jdebacker** [comment]
Relates to now offline C/S app.
